### ISSUE TITLE
Add SSELPH SCRAPER

### ISSUE THREAD

**Issue by MichaelHP** [Death259/PiAssist#10]
Add functionality in PiAssist to install SSEPCH Scraper
https://github.com/sselph/scraper

Add command to scrape art for all folders with roms in them

**Comment by Death259** [comment]
This has been added into PiAssist with one caveat. In order to be able to have the scraped results saved, you must actually quit out of emulation station and run the scraper from command line. I'll work on fixing this caveat, but I wanted to go ahead and publish the scraper as is.

Note for myself: [readme for emulation station gamelist.xml](https://github.com/Aloshi/EmulationStation/blob/master/GAMELISTS.md)

**Comment by Death259** [comment]
As of commit 489bbb32ee57c32153d7e995b3e512a1d1dcf7ee PiAssist will let you know that the scraper cannot be run while Emulation Station is running and then will kick back to the menu.

**Comment by Death259** [comment]
I'm going to consider this enhancement as it is working 100%. I had left the issue open in hopes I might be able to come up with a solution to allow scraping to be done while in Emulation Station, but I'm not sure if that's possible.

**Comment by Death259** [comment]
And I think I goofed... it looks like MAME roms require a special argument in order to be scraped properly. I'll fix that at some point...

**Comment by HerbFargus** [comment]
I know sselph had plans of integrating his scraper into a custom build of emulation station at some point. When that day comes, it will be a great day.

**Comment by Death259** [comment]
As of commit 81712c4f7676ee981b94430f26917e65d1fc6536 mame roms should now be properly scraped. The rom scraper is now given the correct arguments in order for it to recognize that it's scraping mame roms.
