### ISSUE TITLE
Add Splashcreen Changing

### ISSUE THREAD

**Issue by Death259** [Death259/PiAssist#20]
It would be nice if changing the splashcreen could be easy. Allow for letting people use a randomizer, just like in [this reddit post](https://www.reddit.com/r/RetroPie/comments/2ptig2/splashscreen_randomizer/). Also see if we can allow for doing videos as shown [in this youtube video](https://www.youtube.com/watch?v=dIpm_BrwBKo). Lastly, see if we can combine the two.

**Comment by HerbFargus** [comment]
I think that's a brilliant idea- I'm not super skilled at scripting like you are, but I've been trying to sort out the best way to figure out the boot video thing. As of right now I used an older version of Omxplayer on the aforementioned video because with the newest omxplayer- the latest raspberry pi firmware changed the boot sequence so that the dependencies were no longer met (since now it loads the initialisation scripts alphabetically of which asplashscreen is the first.) 

see this post http://piplay.org/forum/discussion/1584/solved-waiting-for-dbus-address-to-appear-after-dist-upgrade/p1  

or this post https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=97693

or this post https://github.com/raspberrypi/firmware/issues/349

In order to use the latest omxplayer (which has better results playing different video types) the simplest way to change it is to change asplashscreen to nsplashscreen or figure out all the dependencies and put them in the required-start perametre. 

I don't know, what are your thoughts on the matter?

**Comment by Death259** [comment]
Hah, looks like you beat me to the punch. Haven't given it too much thought just yet. I'll take a look at the links you provided and what I've found and see what i can do. I'll probably just start with a simple splash screen picture changer and then see about doing the video.

One thought I had was to have the splash randomizer randomly pick from the images that were scraped for the roms. Someone had also mentioned wanting to add audio to Retropie, which was done in recalbox, so perhaps i could do this as well.

**Comment by rodrigosiviero** [comment]
@Death259 feel free to use my splashscreen randomizer, maybe we can workout something in my code to add the video or something else, anything let me know

**Comment by Death259** [comment]
As of commit da9c6d783d34b374d15ce9e1f564c9114edaade5 I've added the ability to choose an individual splashscreen. The randomizer will come later, as well as adding a menu entry to Emulation Station.

The splashscreen video could be a little more complicated, but I will still attempt it once these other easier splashscreen enhancements are added.

Edit:
As of commit e63bd323eaf8d8d101d913476dc159224a45728c a menu entry has been added to emulation station to change the splash screen.

**Comment by Death259** [comment]
As of commit aa0e5b77af6487ea31750b2ea6c0b0f009c532aa a splash screen randomizer can be utilized. This uses the [exact same concept](https://github.com/sur0x/retropiesplashscreen) that [sur0x](https://github.com/sur0x) had already put together, I just rewrote it to make it a little more compact.

**Comment by HerbFargus** [comment]
good work. sorry I haven't been more helpful, I've been busy building scriptmodules for retropie. I'll test out this bit of code and then I may take a whack at this whole video splashscreen thing- at the very least hopefully figure out the dependencies for omxplayer as I'd prefer to install it from a repo with apt-get instead of manually installing an older build and freezing the potential for updates.

**Comment by Death259** [comment]
No worries. I think if we can get the video splash screen to work, then making it randomly choose one should be a breeze.

**Comment by HerbFargus** [comment]
On a quick perusal of your changes- because you named it splashscreen instead of asplashscreen, the latest omxplayer should work without throwing out dbus errors. All you'd have to do is make omxplayer a dependency and adapt this code here:
https://github.com/RetroPie/RetroPie-Setup/pull/668
Replacing mplayer with omxplayer

**Comment by HerbFargus** [comment]
You could probably also get away with adding .avi as an extension as well.

**Comment by Death259** [comment]
Looks fairly promising. I perused the asplashscreen that already exists in /etc/init.d and the changes that were made in the link you provided should be relatively easy. Assuming omxplayer wants to play nicely we will be good. I'll look at this more in-depth another day.

**Comment by HerbFargus** [comment]
I just tested omxplayer (with apt-get install omxplayer) and I changed retropie's default `asplashscreen` to `splashscreen` and it worked swimmingly. because it's further down on the dependency list it runs the video just a bit before emulationstation runs so emulationstation cuts the video off if its more than 2 seconds (on an rpi2) but that's easily remedied by removing & from the code.

**Comment by Death259** [comment]
I'm closing this issue out as this has pretty much been included in default RetroPie.
